version: '3.9'

services:
  redis:
    image: redis:7-alpine
    volumes:
      - redis-prod-data:/data
    healthcheck:
      test: ['CMD', 'redis-cli', 'ping']
      interval: 10s
      timeout: 3s
      retries: 5
    restart: unless-stopped

  api-gateway:
    build:
      context: .
      dockerfile: services/api-gateway/Dockerfile
      target: prod
    volumes:
      - ./services/api-gateway/keys:/app/services/api-gateway/keys:ro
    ports:
      - '3000:3000'
    env_file:
      - services/api-gateway/.env.prod
    depends_on:
      redis:
        condition: service_healthy

volumes:
  redis-prod-data:

